package com.hejwesele.invitations.dto

import androidx.annotation.Keep
import com.hejwesele.remotedatabase.AutoGeneratedId

@Keep
data class InvitationDto(
    @AutoGeneratedId val id: String? = null,
    var tiles: List<InvitationTileDto> = emptyList()
)
