image: openjdk:11-jdk

variables:
  ANDROID_COMPILE_SDK: "31"
  ANDROID_BUILD_TOOLS: "32.0.0"
  ANDROID_COMMAND_LINE_TOOLS: "7583922"
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"


before_script:
  - export GRADLE_USER_HOME=$(pwd)/.gradle
  - chmod +x ./gradlew
  - apt-get --quiet update --yes
  - apt-get --quiet install --yes wget tar unzip lib32stdc++6 lib32z1
  - mkdir -p android-sdk-linux/cmdline-tools
  - export ANDROID_SDK_ROOT=$PWD/android-sdk-linux
  - cd android-sdk-linux/cmdline-tools
  - wget --quiet --output-document=android-sdk.zip https://dl.google.com/android/repository/commandlinetools-linux-${ANDROID_COMMAND_LINE_TOOLS}_latest.zip
  - unzip android-sdk.zip
  - rm android-sdk.zip
  - mv cmdline-tools version
  - echo y | version/bin/sdkmanager "platforms;android-${ANDROID_COMPILE_SDK}" >/dev/null
  - echo y | version/bin/sdkmanager "platform-tools" >/dev/null
  - echo y | version/bin/sdkmanager "build-tools;${ANDROID_BUILD_TOOLS}" >/dev/null
  - export PATH=$PATH:$ANDROID_SDK_ROOT/platform-tools/
  - set +o pipefail
  - yes | version/bin/sdkmanager --licenses
  - set -o pipefail
  - cd ../../
  - chmod +x ./gradlew

stages:
  - test
  - build

# ---DEBUG---

testDebug:
  stage: test
  script:
    - ./gradlew -Pci --console=plain :app:testDebug
  only:
    - /^feat.*$/
    - /^fix.*$/

lintDebug:
  stage: test
  script:
    - ./gradlew -Pci --console=plain :app:lintDebug -PbuildDir=lint
  only:
    - /^feat.*$/
    - /^fix.*$/

assembleDebug:
  stage: build
  script:
    - ./gradlew assembleDebug
  only:
    - /^feat.*$/
    - /^fix.*$/

# ---QA---

testQa:
  stage: test
  script:
    - ./gradlew -Pci --console=plain :app:testQa
  only:
    - develop

lintQa:
  stage: test
  script:
    - ./gradlew -Pci --console=plain :app:lintQa -PbuildDir=lint
  only:
    - develop

assembleQa:
  stage: build
  script:
    - ./gradlew assembleQa
  only:
    - develop
  artifacts:
    paths:
      - app/build/outputs/

# ---RELEASE---

testRelease:
  stage: test
  script:
    - ./gradlew -Pci --console=plain :app:testRelease
  only:
    - main

lintRelease:
  stage: test
  script:
    - ./gradlew -Pci --console=plain :app:lintRelease -PbuildDir=lint
  only:
    - main

assembleRelease:
  stage: build
  script:
    - ./gradlew assembleRelease
  only:
    - main
  artifacts:
    paths:
      - app/build/outputs/
