variables:
  BASE_IMAGE_TAG: "android-$ANDROID_SDK_VERSION-buildtools-$BUILDTOOLS_VERSION-flank-$FLANK_VERSION"

.base:
  image: $CI_REGISTRY_IMAGE:$BASE_IMAGE_TAG
  tags:
    - docker
    - miquido
  before_script:
    # change gradle distribution url to use nexus server
    - sed -i 's~https\\:\/\/services.gradle.org\/~https\\:\/\/nexus.miquido.net\/repository\/gradle\-~g' gradle/wrapper/gradle-wrapper.properties

.flank-tests:
  extends: .base
  interruptible: false
  script:
    - export GCLOUD_DIR="$HOME/.config/gcloud"
    - install -d $GCLOUD_DIR
    - echo ${TEST_LAB_SERVICE_KEY} | base64 --decode > "$GCLOUD_DIR/application_default_credentials.json"
    - ./gradlew --no-daemon --no-configuration-cache --build-cache :app:assembleDebug :app:assembleDebugAndroidTest
    - java -jar $FLANK_HOME/flank.jar firebase test android run -c=flank/$FLANK_ENV
  artifacts:
    when: always
    expire_in: 72 hrs
    paths:
      - "results/**/HtmlErrorReport.html"
      - "results/**/test_result_*.xml"
    reports:
      junit: "results/**/test_result_*.xml"
