package com.hejwesele.events.remote.dto

import androidx.annotation.Keep
import com.hejwesele.realtimedatabase.AutoGeneratedId

@Keep
data class EventDto(
    @field:AutoGeneratedId var id: String? = null,
    val home_tiles: List<HomeTileDto>? = null,
    val name: String? = null
)
