package com.hejwesele.events.dto

import androidx.annotation.Keep
import com.hejwesele.remotedatabase.AutoGeneratedId
import kotlinx.serialization.Serializable

@Keep
@Serializable
data class EventDto(
    @field:AutoGeneratedId var id: String? = null,
    val name: String? = null,
    val password: String? = null,
    val detailsId: String? = null,
    val invitationId: String? = null,
    val scheduleId: String? = null,
    val servicesId: String? = null,
    val galleryId: String? = null
)
